FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY passport/passportServer.js ./
COPY passport/passportDb.js ./
COPY passport/controllers ./passport/controllers
COPY passport/routes ./passport/routes
COPY passport/model ./passport/model

EXPOSE 5000

CMD ["node", "passport/passportServer.js"]
