###
GET http://localhost:13000/setup

###
GET http://localhost:13000

###

GET http://localhost:13000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzYwMDA1MzUzLCJleHAiOjE3NjAwMDUzNjh9.0AEmhv7dyRzd4cPFua0TGdQSGnEa4typ_dzQv2U_cJU
###
POST http://localhost:4000/auth/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzYwMDA1MzUzfQ.QeT0z91jA5RyS0i1DBJn_asSpePAIo_byyHGn-koubg"
}

###

POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Gonçalo",
  "lastname": "Gaspar",
  "age": 22,
  "username": "doutorgaspar",
  "email": "doutorgaspar@gmail.com",
  "password": "12345678",
  "musical_genre": ["pimba"]
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "doutorgaspar@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:4000/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJzaW5jb3BzZSIsImVtYWlsIjoic2luY29wc2VAZ21haWwuY29tIiwiaWF0IjoxNzYwMDE4Mjc4fQ.nV9d-xm_B7_Ymqq2dZnB8fNg6CvTHPKaKh0kvtw24Vg"
}

###
GET http://localhost:13000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJzaW5jb3BzZSIsImVtYWlsIjoic2luY29wc2VAZ21haWwuY29tIiwiaWF0IjoxNzYwMDE4ODY2LCJleHAiOjE3NjAwMTg4ODF9.WAnLk1o8j9J4XgPTRGp8dhG0DGLIBBOyyJMdkKvjqSo