### Register user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Alexandre",
  "lastname": "Marques",
  "birthdate": "2003-05-29",
  "username": "alexpm",
  "email": "alexpm@example.com",
  "password": "12345678",
  "genres": ["Rock", "Pop"]
}
### Register user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Grande",
  "lastname": "Nabo",
  "birthdate": "1897-02-05",
  "username": "nabinho",
  "email": "nabinho@example.com",
  "password": "12345678",
  "genres": ["Metal", "Jazz"]
}

### Login user
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "alexpm",
  "password": "12345678"
}

### Login user
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "zescopse",
  "password": "12345678"
}

### Refresh token
POST http://localhost:4000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTE5NTcyNSwiZXhwIjoxNzY1ODAwNTI1fQ.YCqxvpOfNfGjW6MkoYHg5Kd_ZxGG3wvpa4OWHISroXw"
}

### Logout user
POST http://localhost:4000/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDg1NTc2MywiZXhwIjoxNzY1NDYwNTYzfQ.gwmrC9DtwQvmW2qFnr7esjSCLLn7l-78f7d5MZHjhlw"
}

### Get user profile (authenticated)
GET http://localhost:4000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NTE5NTc0NSwiZXhwIjoxNzY1MTk2NjQ1fQ.vxKpumEi4qEzaEXfNLD86K1zhg8LmMjU3Bt1bep00Ts

### Update user profile (authenticated)
PATCH http://localhost:4000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NTE5NTc0NSwiZXhwIjoxNzY1MTk2NjQ1fQ.vxKpumEi4qEzaEXfNLD86K1zhg8LmMjU3Bt1bep00Ts
Content-Type: application/json

{
  "name": "Alexandre",
  "lastname": "Marques",
  "birthdate": "2003-05-29"
}

### Change password (authenticated)
PATCH http://localhost:4000/user/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NTE5NTc0NSwiZXhwIjoxNzY1MTk2NjQ1fQ.vxKpumEi4qEzaEXfNLD86K1zhg8LmMjU3Bt1bep00Ts
Content-Type: application/json

{
  "currentPassword": "newpassword123",
  "newPassword": "12345678"
}

### Get user preferences (authenticated)
GET http://localhost:4000/user/preferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NTE5NTc0NSwiZXhwIjoxNzY1MTk2NjQ1fQ.vxKpumEi4qEzaEXfNLD86K1zhg8LmMjU3Bt1bep00Ts

### Update user preferences (authenticated)
PATCH http://localhost:4000/user/preferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NTE5NTc0NSwiZXhwIjoxNzY1MTk2NjQ1fQ.vxKpumEi4qEzaEXfNLD86K1zhg8LmMjU3Bt1bep00Ts
Content-Type: application/json

{
  "genres": ["Jazz", "Electronic"]
}

### Admin: Get all users (authenticated)
GET http://localhost:4000/user/allusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTE5NjAzNCwiZXhwIjoxNzY1MTk2OTM0fQ.no0KGCiV4RCs0F8K4kcs6Aw06N8IpniB4nqJT-dYRSY

### Admin: Delete a user by ID (authenticated)
DELETE http://localhost:4000/user/deleteuser/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTIxMDQ0OSwiZXhwIjoxNzY1MjExMzQ5fQ.OSQpYTuO65-b5tXYTbbAXQ7XJBdLPv5DLeVzyXGemdY

### Admin: Update a user's role by ID (authenticated)
PATCH http://localhost:4000/user/7/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTIwNjI0OCwiZXhwIjoxNzY1MjA3MTQ4fQ.bFdazmA_7h7O9Skl55hAgc1BpGhUWl1dt6XWC9JaIUY
Content-Type: application/json

{
  "role": "admin"
}

