### Register user
POST http://localhost:4000/users/auth/register
Content-Type: application/json

{
  "name": "João",
  "lastname": "Silva",
  "birthdate": "1990-05-10",
  "username": "joaosilva",
  "email": "joao@example.com",
  "password": "12345678",
  "genres": ["Rock", "Jazz"]
}

### Login user
POST http://localhost:4000/users/auth/login
Content-Type: application/json

{
  "username": "joaotest",
  "password": "123456"
}

### Refresh token
POST http://localhost:4000/users/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Fvc2lsdmEiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ0MzYyODJ9.0-56iGJQXMAlm8gQQA5ZGOgTfsM7wnnbkaF9SUuvSJE"
}

### Logout user
POST http://localhost:4000/users/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb2FvdGVzdCIsImVtYWlsIjoiam9hb0BtYWlsLmNvbSIsImlhdCI6MTc2NDQzNjgxOH0.Q7XxLQWjkwe7NOG4LniZPdSCUiZHMaQjiS3yKzxRJ-Y"
}

### Get user profile (authenticated)
GET http://localhost:4000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Fvc2lsdmEiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ0MzY4MDEsImV4cCI6MTc2NDQzNzcwMX0.HLhyurEOgp80-ToJ6UbrHVler1VuKBXpPMHBn6Uuk84

### Update user profile (authenticated)
PATCH http://localhost:4000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Fvc2lsdmEiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ0MzY4MDEsImV4cCI6MTc2NDQzNzcwMX0.HLhyurEOgp80-ToJ6UbrHVler1VuKBXpPMHBn6Uuk84
Content-Type: application/json

{
  "name": "João Carlos",
  "lastname": "Neto Silva",
  "birthdate": "1990-05-10"
}

### Get user preferences (authenticated)
GET http://localhost:4000/users/userpreferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Fvc2lsdmEiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ0MzY4MDEsImV4cCI6MTc2NDQzNzcwMX0.HLhyurEOgp80-ToJ6UbrHVler1VuKBXpPMHBn6Uuk84

### Update user preferences (authenticated)
PATCH http://localhost:4000/users/userpreferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Fvc2lsdmEiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ0MzY4MDEsImV4cCI6MTc2NDQzNzcwMX0.HLhyurEOgp80-ToJ6UbrHVler1VuKBXpPMHBn6Uuk84
Content-Type: application/json

{
  "genres": ["Rock", "Electronic"]
}

### Get user posts (authenticated)
GET http://localhost:4000/users/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Fvc2lsdmEiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ0MzY4MDEsImV4cCI6MTc2NDQzNzcwMX0.HLhyurEOgp80-ToJ6UbrHVler1VuKBXpPMHBn6Uuk84
