### Register user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Alexandre",
  "lastname": "Marques",
  "birthdate": "2003-05-29",
  "username": "alexpm",
  "email": "alexpm@example.com",
  "password": "12345678",
  "genres": ["Rock", "Pop"]
}

### Login user
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "alexpm",
  "password": "12345678"
}

### Refresh token
POST http://localhost:4000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDg1NTc2MywiZXhwIjoxNzY1NDYwNTYzfQ.gwmrC9DtwQvmW2qFnr7esjSCLLn7l-78f7d5MZHjhlw"
}

### Logout user
POST http://localhost:4000/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDg1NTc2MywiZXhwIjoxNzY1NDYwNTYzfQ.gwmrC9DtwQvmW2qFnr7esjSCLLn7l-78f7d5MZHjhlw"
}

### Get user profile (authenticated)
GET http://localhost:4000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NDg1NTc3MSwiZXhwIjoxNzY0ODU2NjcxfQ.dBMLLwVMbuckBo7geLEp9rsq4aa25-e7SOEOa5pcbOg

### Update user profile (authenticated)
PATCH http://localhost:4000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NDg1NTc3MSwiZXhwIjoxNzY0ODU2NjcxfQ.dBMLLwVMbuckBo7geLEp9rsq4aa25-e7SOEOa5pcbOg
Content-Type: application/json

{
  "name": "Alexandre",
  "lastname": "Marques",
  "birthdate": "1990-05-10"
}

### Change password (authenticated)
PATCH http://localhost:4000/user/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NDg1NTc3MSwiZXhwIjoxNzY0ODU2NjcxfQ.dBMLLwVMbuckBo7geLEp9rsq4aa25-e7SOEOa5pcbOg
Content-Type: application/json

{
  "currentPassword": "12345678",
  "newPassword": "newpassword123"
}

### Get user preferences (authenticated)
GET http://localhost:4000/user/preferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NDg1NTc3MSwiZXhwIjoxNzY0ODU2NjcxfQ.dBMLLwVMbuckBo7geLEp9rsq4aa25-e7SOEOa5pcbOg

### Update user preferences (authenticated)
PATCH http://localhost:4000/user/preferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NDg1NTc3MSwiZXhwIjoxNzY0ODU2NjcxfQ.dBMLLwVMbuckBo7geLEp9rsq4aa25-e7SOEOa5pcbOg
Content-Type: application/json

{
  "genres": ["Rock", "Electronic"]
}

### Get user posts (authenticated)
GET http://localhost:4000/user/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NDg1NTc3MSwiZXhwIjoxNzY0ODU2NjcxfQ.dBMLLwVMbuckBo7geLEp9rsq4aa25-e7SOEOa5pcbOg

### Admin: Get all users (authenticated)
GET http://localhost:4000/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDg1NTg2NCwiZXhwIjoxNzY0ODU2NzY0fQ.2rjk43Gw2Px84CORZrBThS1r_xviLwR0FaC_zNHU4gI

### Admin: Delete a user by ID (authenticated)
DELETE http://localhost:4000/admin/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDg1NTg2NCwiZXhwIjoxNzY0ODU2NzY0fQ.2rjk43Gw2Px84CORZrBThS1r_xviLwR0FaC_zNHU4gI

### Admin: Update a user's role by ID (authenticated)
PATCH http://localhost:4000/admin/users/1/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY3OTM5MCwiZXhwIjoxNzY0NjgwMjkwfQ.y3X0i0Zk8w2BE87lMH3IMLIo8qrJsEtmJnwiwxoMKuU
Content-Type: application/json

{
  "role": "user"
}

### Admin: Get all genres (authenticated)
GET http://localhost:4000/admin/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDg1NTg2NCwiZXhwIjoxNzY0ODU2NzY0fQ.2rjk43Gw2Px84CORZrBThS1r_xviLwR0FaC_zNHU4gI

