const pool = require("./concertsDb");

async function createTables() {
  try {
    // Users
    await pool.query(`
      CREATE TABLE IF NOT EXISTS "market_place_post" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "description" text,
  "suggested_price" decimal(10,2),
  "ticket_quantity" integer,
  "status" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "image_url" varchar(250)
);
    `);
    console.log("Tables created or already exist.");
  } catch (err) {
    console.error("Error creating tables:", err);
    process.exit(1);
  }
}

module.exports = createTables;
