# Deployment do Backstage Auth Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-auth
  namespace: backstage
  labels:
    app: backstage-auth
    component: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backstage-auth
  template:
    metadata:
      labels:
        app: backstage-auth
        component: auth
    spec:
      containers:
      - name: backstage-auth
        # ALTERE PARA SUA CONTA DOCKER HUB
        image: alexmarques11/backstage-auth:latest
        # image: goncalocruz/backstage-auth:latest
        # image: zeaccount/backstage-auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
        env:
        # Configurações do ConfigMap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backstage-config
              key: NODE_ENV
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: backstage-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: backstage-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backstage-config
              key: DATABASE_NAME
        
        # Configurações sensíveis do Secret
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: DATABASE_PASSWORD
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: ACCESS_TOKEN_SECRET
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: REFRESH_TOKEN_SECRET
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /auth/token
            port: 4000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /auth/token
            port: 4000
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        
        # Resource limits
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"

---
# Service para Backstage Auth Server
apiVersion: v1
kind: Service
metadata:
  name: backstage-auth-service
  namespace: backstage
  labels:
    app: backstage-auth
    component: auth
spec:
  selector:
    app: backstage-auth
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  type: ClusterIP