### Test Posts Endpoints

### Variables
@baseUrl = http://localhost:3003
@postId = 1
@userId = 1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhbGV4cG0iLCJlbWFpbCI6ImFsZXhwbUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY1MjQwNTUwLCJleHAiOjE3NjUyNDE0NTB9.iE9fxU-HWMrLAwp51ZvPfZXlaC0XIlybwRaHk1auTZk

### Get all posts
GET {{baseUrl}}/publications

### Get post by ID
GET {{baseUrl}}/publications/{{postId}}

### Get post with filter
GET {{baseUrl}}/publications?title=Balls&location=Guimarães

### Delete a post
DELETE {{baseUrl}}/publications/{{postId}}
Authorization: Bearer {{token}}

### Create Concert
POST {{baseUrl}}/publications
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 1,
  "title": "Rock Festival 2025",
  "description": "Amazing rock festival",
  "date": "2025-12-20T20:00:00Z",
  "location": 1,
  "genres": [1],
  "image_url": "https://example.com/image.jpg"
}

### Update Concert
PUT {{baseUrl}}/publications/11
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Rock Festival 2025",
  "description": "Even more amazing",
  "date": "2025-12-21T20:00:00Z"
}