#!/bin/bash

echo "🔧 DigitalOcean Authentication Troubleshooter"
echo "============================================="

echo ""
echo "🔍 Current authentication status:"
echo "Context: $(doctl auth list | grep current || echo 'No current context')"

echo ""
echo "🧪 Testing API access..."
if doctl account get &>/dev/null; then
    echo "✅ Authentication working"
    echo "Account info:"
    doctl account get --format Email,Status,Team
else
    echo "❌ Authentication failed"
    echo ""
    echo "📋 Common issues and solutions:"
    echo ""
    echo "1. **Wrong Token Scope**"
    echo "   • Your token needs BOTH read AND write permissions"
    echo "   • Go to: https://cloud.digitalocean.com/account/api/tokens"
    echo "   • Create new token with 'Read' and 'Write' scopes"
    echo ""
    echo "2. **Token Expired**"
    echo "   • Check if your token has expired"
    echo "   • Create a new token if needed"
    echo ""
    echo "3. **Wrong Token Format**"
    echo "   • Make sure you copied the entire token"
    echo "   • Token should be 64 characters long"
    echo ""
    echo "4. **Account Issues**"
    echo "   • Make sure your DigitalOcean account is active"
    echo "   • Check if you have billing information set up"
    echo ""
    echo "🔧 To fix:"
    echo "   1. Create new token: https://cloud.digitalocean.com/account/api/tokens"
    echo "   2. Run: doctl auth init"
    echo "   3. Paste your new token"
    echo "   4. Run: doctl account get (to test)"
fi

echo ""
echo "🔍 If you need to switch contexts:"
echo "   doctl auth init --context new-context-name"
echo ""
echo "🔍 To remove current context and start fresh:"
echo "   doctl auth remove --context default"
echo "   doctl auth init"