name: Android CI

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'backstage_frontend/**'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'backstage_frontend/**'
      - '.github/workflows/android-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      working-directory: backstage_frontend
      run: chmod +x gradlew

    - name: Run unit tests
      working-directory: backstage_frontend
      run: ./gradlew test

    - name: Run lint checks
      working-directory: backstage_frontend
      run: ./gradlew lint

    - name: Build debug APK
      working-directory: backstage_frontend
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: backstage_frontend/app/build/outputs/apk/debug/*.apk

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: backstage_frontend/app/build/reports/tests/

    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: backstage_frontend/app/build/reports/lint-results-debug.html

  instrumented-tests:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      working-directory: backstage_frontend
      run: chmod +x gradlew

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: default
        arch: x86_64
        script: |
          cd backstage_frontend
          ./gradlew connectedAndroidTest

    - name: Upload instrumented test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: instrumented-test-results
        path: backstage_frontend/app/build/reports/androidTests/